steps:
# Deploy the test workflow with the commit sha
- id: 'deploy-test-workflow'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['workflows', 'deploy', 'mbcs$_WORKFLOW_NAME-$BRANCH_NAME-$SHORT_SHA', '--source', 'cicd/workflow.yaml']

- id: 'run-workflow'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'gcloud'
  args: [ 'beta', 'workflows', 'run', 'mbcs$_WORKFLOW_NAME-$BRANCH_NAME-$SHORT_SHA',  '--data',
          '{"repository": "${_REPOSITORY}", "dataset": "${_DATASET}", "branch": "$BRANCH_NAME", "full_refresh": "${_FULL_REFRESH}", "gcp_project": "$PROJECT_ID"}',
          '--call-log-level', 'log-all-calls'
  ]